language: python
python:
- 3.7
before_script:
- pip install coverage
- pip install coveralls
- pip install numpy
- pip install pandas
script:
- coverage run --source=fast_csv test_fast_csv.py
after_success:
- coveralls
deploy:
  skip_existing: true
  provider: pypi
  user: yux-io
  password: ${PYPI_PASSWORD}
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: YUX-IO/fast_csv
  skip_cleanup: 'true'
