language: python
python:
- 3.7
before_script:
- pip install coverage
- pip install coveralls
- pip install numpy
- pip install pandas
script:
- coverage run test_fast_csv.py
after_success:
- coveralls